-- DDL generado desde SQL Server local para Montero_db (PostgreSQL)
CREATE SCHEMA IF NOT EXISTS public;

-- meta_venta_neta (113126 filas en origen)
DROP TABLE IF EXISTS public.meta_venta_neta CASCADE;
CREATE TABLE public.meta_venta_neta (
  idregistro numeric(18,0) NOT NULL,
  periodo varchar(6) NOT NULL,
  local varchar(100),
  bodega numeric(18,0),
  nombre_bodega varchar(100),
  bien_servicio varchar(1) NOT NULL,
  codigo varchar(20),
  descripcion varchar(255),
  movimiento varchar(50),
  serie numeric(10,0),
  numero numeric(10,0),
  fecha timestamp,
  trimestre integer,
  semana integer,
  dia integer,
  diay integer,
  dias varchar(25),
  hora integer,
  cantidad numeric(18,6),
  costou numeric(18,6),
  costo numeric(18,6),
  precio numeric(18,6),
  iva numeric(18,6),
  dcto_subtotal_neto numeric(18,2),
  dcto_neto numeric(18,2),
  dcto_iva_neto numeric(18,2),
  venta_neta numeric(18,2),
  utilidad numeric(18,2),
  vendedor varchar(50),
  ruc varchar(15),
  nombre_completo varchar(255),
  alterno varchar(20),
  alterno1 varchar(20),
  alterno2 varchar(20),
  cod_clasificacion1 varchar(10),
  cod_clasificacion2 varchar(10),
  cod_clasificacion3 varchar(10),
  cod_clasificacion4 varchar(10),
  cod_clasificacion5 varchar(10),
  cod_clasificacion6 varchar(10),
  cod_clasificacion7 varchar(10),
  cod_clasificacion8 varchar(10),
  cod_clasificacion9 varchar(10),
  cod_clasificacion10 varchar(10),
  clasificacion1 varchar(50),
  clasificacion2 varchar(50),
  clasificacion3 varchar(50),
  clasificacion4 varchar(50),
  clasificacion5 varchar(50),
  clasificacion6 varchar(50),
  clasificacion7 varchar(50),
  clasificacion8 varchar(50),
  clasificacion9 varchar(50),
  clasificacion10 varchar(50),
  cod_clas_cliente1 varchar(10),
  cod_clas_cliente2 varchar(10),
  cod_clas_cliente3 varchar(10),
  cod_clas_cliente4 varchar(10),
  cod_clas_cliente5 varchar(10),
  cod_clas_cliente6 varchar(10),
  cod_clas_cliente7 varchar(10),
  cod_clas_cliente8 varchar(10),
  cod_clas_cliente9 varchar(10),
  cod_clas_cliente10 varchar(10),
  clas_cliente1 varchar(50),
  clas_cliente2 varchar(50),
  clas_cliente3 varchar(50),
  clas_cliente4 varchar(50),
  clas_cliente5 varchar(50),
  clas_cliente6 varchar(50),
  clas_cliente7 varchar(50),
  clas_cliente8 varchar(50),
  clas_cliente9 varchar(50),
  clas_cliente10 varchar(50),
  clas_factura1 varchar(50),
  clas_factura2 varchar(50),
  clas_factura3 varchar(50),
  clas_factura4 varchar(50),
  clas_factura5 varchar(50),
  clas_factura6 varchar(50),
  clas_factura7 varchar(50),
  clas_factura8 varchar(50),
  clas_factura9 varchar(50),
  clas_factura10 varchar(50),
  ctas_ventas varchar(20),
  ctas_costo varchar(20),
  ctas_desc varchar(20),
  ctas_desc1 varchar(20),
  ctas_desc2 varchar(20),
  ctas_devolucion varchar(20),
  ctas_dev_dcto varchar(20),
  ctas_dev_dcto1 varchar(20),
  ctas_dev_dcto2 varchar(20),
  provincia varchar(50),
  canton varchar(50),
  parroquia varchar(50),
  alter_desc varchar(50),
  alter_desc1 varchar(50),
  alter_desc2 varchar(50),
  factor_c numeric(18,6),
  factor_cantidad numeric(18,6),
  control_fec_creacion timestamp,
  control_spid integer,
  ice_neto numeric(18,2),
  base_ice numeric(18,2),
  porcentaje_ice numeric(18,2),
  anio integer,
  proyecto varchar(100),
  concepto varchar(100),
  vendedor2 varchar(50)
);

-- FAC_FACTURAS (26021 filas en origen)
DROP TABLE IF EXISTS public.fac_facturas CASCADE;
CREATE TABLE public.fac_facturas (
  ffg_serie numeric(10,0) NOT NULL,
  ffg_numero numeric(10,0) NOT NULL,
  fve_codigo integer,
  fcl_codigo numeric(15,0),
  fac_guia_numero varchar(50),
  ffg_fecha timestamp,
  ffg_cartera numeric(10,0),
  ffg_pedido numeric(10,0),
  ffg_anulado varchar(1),
  ffg_impresa varchar(1),
  ffg_subtotal numeric(15,2),
  ffg_descuento numeric(5,2),
  ffg_valdesc numeric(15,2),
  ffg_valdesc1 numeric(15,2),
  ffg_valdesc2 numeric(15,2),
  ffg_iva0 numeric(15,2),
  ffg_iva numeric(15,2),
  ffg_viva numeric(15,2),
  ffg_total numeric(15,2),
  ffg_forma varchar(1),
  ffg_efectivo numeric(15,2),
  ffg_cheque numeric(15,2),
  ffg_tarjeta numeric(15,2),
  ffg_credito numeric(15,2),
  ffg_vence timestamp,
  ffg_fec_anulacion timestamp,
  ffg_caja varchar(20),
  ffg_anticipos numeric(15,2),
  ffg_num_tarjeta varchar(25),
  ffg_codigo_tarjeta varchar(10),
  ffg_ajuste numeric(15,2),
  ffg_reportado varchar(1),
  ffg_num_trj_2 varchar(25),
  ffg_cod_trj_2 varchar(10),
  ffg_val_trj_2 numeric(15,2),
  ffg_num_trj_3 varchar(25),
  ffg_num_trj_4 varchar(25),
  ffg_num_trj_5 varchar(25),
  ffg_cod_trj_3 varchar(10),
  ffg_cod_trj_4 varchar(10),
  ffg_cod_trj_5 varchar(10),
  ffg_val_trj_3 numeric(15,2),
  ffg_val_trj_4 numeric(15,2),
  ffg_val_trj_5 numeric(15,2),
  ffg_servicios numeric(15,2),
  ffg_propinas numeric(15,2),
  ffg_lote_1 varchar(15),
  ffg_lote_2 varchar(15),
  ffg_lote_3 varchar(15),
  ffg_lote_4 varchar(15),
  ffg_lote_5 varchar(15),
  ffg_usuario_emite varchar(10),
  ffg_usuario_anula varchar(10),
  ffg_sucursal integer,
  ffg_iva_bienes numeric(20,6),
  ffg_iva_servicios numeric(20,6),
  ffg_base_retencion numeric(20,6),
  ffg_baseimponible numeric(12,2),
  ffg_baseimpgrav numeric(12,2),
  ffg_basenoiva numeric(12,2),
  ffg_ruc_ci varchar(15),
  ffg_nombre_alterno varchar(150),
  ffg_carrera varchar(150),
  ffg_nivel varchar(25),
  ffg_academico numeric(10,0),
  ffg_dep_num varchar(25),
  ffg_dep_val numeric(12,2),
  ffg_dep_banco varchar(25),
  ffg_dep_fecha timestamp,
  ffg_clas_dcto varchar(2),
  ffg_iniciatraslado timestamp,
  ffg_fintraslado timestamp,
  ffg_puntoemision varchar(300),
  ffg_puntopartida varchar(300),
  ffg_transportista varchar(100),
  ffg_idtransportista varchar(13),
  ffg_municipio numeric(12,2),
  ffg_paciente varchar(1000),
  ffg_lote varchar(50),
  ffg_fecha_venc_producto timestamp,
  ffg_medico varchar(100),
  ffg_imprenta3xmil numeric(15,2),
  ffg_ivapresuntivo numeric(15,2),
  ffg_otrovalor numeric(15,2),
  ffg_referencia varchar(500),
  ffg_retencionfte numeric(15,2),
  ffg_retencioniva numeric(15,2),
  ffg_diferencia_iva numeric(12,6),
  ffg_ret_num varchar(20),
  ffg_ret_autor varchar(50),
  ffg_ret_fecha timestamp,
  ffg_ret_caduca timestamp,
  ffg_despachado varchar(1),
  ffg_serie_pedido numeric(10,0),
  ffg_local integer,
  ffg_cod_trj_bmt varchar(10),
  ffg_num_trj_bmt varchar(25),
  ffg_val_trj_bmt numeric(15,2),
  ffg_lote_bmt varchar(10),
  ffg_retencionfteserv numeric(15,2),
  ffg_retencionivaserv numeric(15,2),
  ffg_cod_trj_iata varchar(10),
  ffg_num_trj_iata varchar(25),
  ffg_val_trj_iata numeric(15,2),
  ffg_lote_iata varchar(10),
  ffg_autoriza_comp1 varchar(25),
  ffg_autoriza_comp2 varchar(25),
  ffg_autoriza_comp3 varchar(25),
  ffg_autoriza_comp4 varchar(25),
  ffg_autoriza_comp5 varchar(25),
  ffg_autoriza_comp_bmt varchar(25),
  ffg_autoriza_comp_iata varchar(25),
  ffg_usuario_autoriza varchar(10),
  ffg_pago_comision varchar(1),
  ffg_pago_fecha timestamp,
  ffg_pago_usuario varchar(10),
  ffg_sgn_registro numeric(10,0),
  ffg_numcica numeric(10,0),
  ffg_autorizacion varchar(50),
  ffg_codnumerico varchar(23),
  ffg_clamovim varchar(50),
  ffg_codigo_comprobante varchar(2),
  ffg_claveacceso varchar(49),
  ffg_claveaccesoctg varchar(49),
  ffg_baseafiva numeric(15,2),
  ffg_baseafiva0 numeric(15,2),
  ffg_exportacion varchar(1),
  ffg_baseexportbien numeric(15,2),
  ffg_baseexportserv numeric(15,2),
  ffg_xml varchar(1),
  ffg_parterel varchar(2),
  ffg_correo_enviado varchar(1),
  ffg_serie_prof numeric(10,0),
  ffg_numero_prof numeric(10,0),
  ffg_numero_pedido numeric(10,0),
  ffg_serie_hoja numeric(10,0),
  ffg_numero_hoja numeric(10,0),
  fve_codigo2 integer,
  ffg_contrato varchar(10),
  ffg_cuota integer,
  ffg_observaciones varchar(300),
  ffg_formapago_efectivo integer,
  ffg_formapago_cheque integer,
  ffg_formapago_credito integer,
  ffg_formapago_tarjeta1 integer,
  ffg_formapago_tarjeta2 integer,
  ffg_formapago_tarjeta3 integer,
  ffg_formapago_tarjeta4 integer,
  ffg_formapago_tarjeta5 integer,
  ffg_venceimpresion timestamp,
  ffg_reg_auto integer,
  ffg_valservicio numeric(15,2),
  ffg_num_ficha numeric(20,0),
  ffg_modelo_ficha varchar(1),
  ffg_tipoges_compromiso varchar(250),
  ffg_numges_compromiso integer,
  ffg_numges_registro integer,
  ffg_ciudad varchar(150),
  ffg_origen_carga integer,
  ffg_origen_carga_usuario varchar(35),
  ffg_origen_carga_fecha timestamp,
  ffg_tipocliente varchar(150),
  ffg_peso_bruto numeric(20,6),
  ffg_tara numeric(20,6),
  ffg_peso_neto numeric(20,6),
  ffg_acidez numeric(20,6),
  ffg_humedad numeric(20,6),
  ffg_impureza numeric(20,6),
  ffg_serie_ticket integer,
  ffg_numero_ticket numeric(10,0),
  ffg_bono varchar(1),
  ffg_serie_ref numeric(10,0),
  ffg_numero_ref numeric(10,0),
  ffg_valor_bono numeric(20,6),
  ffg_serie_ne integer,
  ffg_numero_ne numeric(10,0),
  ffg_presupuesto varchar(20),
  ffg_producto varchar(50),
  ffg_marca varchar(50),
  ffg_ordencompra varchar(50),
  ffg_nombre_autoriza varchar(100),
  ffg_inserta_cs integer,
  ffg_entrega integer,
  ffg_contabilizacion varchar(20),
  ffg_incoterm varchar(50),
  ffg_partidasugerida varchar(50),
  ffg_pesoneto varchar(50),
  ffg_pesobruto varchar(50),
  ffg_guia_numero varchar(20),
  ffg_cliente_orig numeric(15,0),
  ffg_anulado_trj varchar(1),
  ffg_nc_serie_trj numeric(10,0),
  ffg_nc_numero_trj numeric(10,0),
  ffg_cartera_vencida numeric(15,2),
  ffg_placa varchar(10),
  ffg_valor_tjt_regalo numeric(12,2),
  ffg_dinrecibido numeric(15,2),
  ffg_pedido_ecommerce numeric(10,0),
  ffg_fecha_entrega timestamp,
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer,
  ffg_reingreso varchar(1),
  ffg_valordemanda numeric(15,2),
  ffg_vice numeric(15,2),
  ffg_ordenremision varchar(15),
  ffg_hojaentrada varchar(8),
  ffg_apropiacion varchar(10),
  ffg_acuerdo_pago varchar(300),
  ffg_libera_puntos varchar(1),
  ffg_numfac_segurob numeric(10,0),
  ffg_usodatos_autoriza varchar(2),
  ffg_usodatos_usuario varchar(35),
  ffg_transferencia numeric(15,2),
  ffg_usodatos_fecha timestamp
);

-- FAC_FACTURA_DETALLE (109617 filas en origen)
DROP TABLE IF EXISTS public.fac_factura_detalle CASCADE;
CREATE TABLE public.fac_factura_detalle (
  ffg_serie numeric(10,0) NOT NULL,
  ffg_numero numeric(10,0) NOT NULL,
  tbs_codigo varchar(20) NOT NULL,
  ffd_registro integer NOT NULL,
  ffd_factura_cartera varchar(20),
  ffd_cantidad numeric(20,6),
  ffd_precio numeric(20,6),
  ffd_descuento numeric(5,2),
  ffd_descuento1 numeric(5,2),
  ffd_descuento2 numeric(5,2),
  ffd_iva numeric(5,2),
  ffd_bodega integer,
  ffd_total numeric(20,6),
  ffd_adicional numeric(20,6),
  ffd_dcto_neto numeric(20,2),
  ffd_iva_neto numeric(20,2),
  ffd_precio_neto numeric(20,2),
  ffd_dcto_neto1 numeric(20,2),
  ffd_dcto_neto2 numeric(20,2),
  ffd_proyecto varchar(10),
  ffd_concepto varchar(5),
  ffd_descripcion varchar(3000),
  ffd_aplicapuntos varchar(1),
  ffd_puntos numeric(15,2),
  ffd_cajas numeric(20,6),
  ffd_piezas numeric(20,6),
  ffd_num_serie varchar(50),
  ffd_recargo numeric(20,6),
  ffd_desc_aut_por varchar(150),
  ffd_num_tarjeta varchar(25),
  ffd_aut_compra varchar(25),
  ffd_dcto_caja varchar(1),
  ffd_fre_serie numeric(10,0),
  ffd_fre_numero numeric(10,0),
  ffd_fre_desc varchar(1),
  ffd_fecha_cartera timestamp,
  ffd_prov_cartera varchar(80),
  ffd_ruc_cartera varchar(14),
  ffd_cod_presupuesto varchar(20),
  ffd_des_presupuesto varchar(40),
  ffd_lote_prod varchar(50),
  ffd_por_servicio numeric(12,2),
  ffd_servicio numeric(12,6),
  ffd_servicio_neto numeric(20,2),
  ffd_proveedor varchar(300),
  ffd_ruc varchar(25),
  ffd_factura varchar(25),
  ffd_pedido numeric(10,0),
  ffd_serie_ne integer,
  ffd_numero_ne numeric(10,0),
  ffd_reg_pedido integer,
  ffd_referencia varchar(20),
  ffd_cod_prmocion integer,
  ffd_clamovim varchar(10),
  ffd_registro_pedido numeric(10,0),
  ffd_serie_opt integer,
  ffd_numero_opt numeric(10,0),
  ffd_registro_dopt integer,
  ffd_descuento_autorizado numeric(5,2),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer,
  ffd_ice_neto numeric(20,2),
  ffd_cod_alterno varchar(150),
  ffd_req_prof integer,
  ffd_serie_prof integer,
  ffd_numero_prof numeric(10,0),
  ffd_opcion_prof integer,
  ffd_item_prof integer,
  ffd_ice numeric(5,2),
  ffd_base_ice numeric(20,6),
  ffd_seguro_bici varchar(2),
  ffd_segb_beneficiario varchar(30),
  ffd_segb_cedulabenef varchar(13),
  ffd_segb_externo varchar(1),
  ffd_cod_menu varchar(10),
  ffd_reg_mesa integer,
  ffd_reg_auto integer,
  ffg_descripcion_adicional varchar(300),
  ffd_registro_insumo integer,
  ffd_reg_insumo integer,
  ffd_tipo_despacho varchar(1),
  ffd_momento_despacho varchar(1),
  ffd_fecha_entrega timestamp,
  ffd_dot_id integer,
  ffd_codigo_alterno varchar(20),
  ffd_descripcion_alterno varchar(300)
);

-- FAC_CLIENTES (2714 filas en origen)
DROP TABLE IF EXISTS public.fac_clientes CASCADE;
CREATE TABLE public.fac_clientes (
  fcl_codigo numeric(15,0) NOT NULL,
  fcl_nombre varchar(100),
  fcl_apellido1 varchar(100),
  fcl_apellido2 varchar(100),
  fcl_nombre_completo varchar(150),
  fcl_razon varchar(100),
  fcl_ruc varchar(14),
  fcl_direccion varchar(250),
  fcl_telefono varchar(250),
  fcl_mail varchar(100),
  fcl_gerente varchar(40),
  fcl_contacto varchar(40),
  fcl_factura varchar(1),
  fcl_deuda numeric(15,2),
  fcl_cobrar varchar(20),
  fcl_anticipo varchar(20),
  fcl_ventas varchar(20),
  fcl_costo_ventas varchar(20),
  fcl_descuentos varchar(20),
  fcl_devolucion varchar(20),
  fcl_credito integer,
  fcl_descuento numeric(5,2),
  fcl_limite numeric(14,2),
  fcl_observaciones varchar(500),
  fcl_tipo1 varchar(1),
  fcl_telefono1 varchar(50),
  fcl_tipo2 varchar(1),
  fcl_telefono2 varchar(50),
  fcl_tipo3 varchar(1),
  fcl_telefono3 varchar(50),
  fcl_tipo4 varchar(1),
  fcl_telefono4 varchar(50),
  fcl_tipo5 varchar(1),
  fcl_telefono5 varchar(50),
  fcl_consumidor varchar(1),
  fcl_anticipos numeric(15,2),
  fcl_cuenta_anticipo varchar(20),
  fcl_dato1 varchar(10),
  fcl_dato2 varchar(10),
  fcl_dato3 varchar(10),
  fcl_dato4 varchar(10),
  fcl_direccion2 varchar(500),
  fcl_imprime varchar(1),
  fcl_cumple timestamp,
  fcl_titulo varchar(10),
  fcl_tipo_dir1 varchar(1),
  fcl_tipo_dir2 varchar(1),
  fcl_ciudad varchar(25),
  fcl_pais varchar(25),
  fcl_bodega integer,
  fcl_vendedor integer,
  fcl_activo varchar(1),
  fcl_tipoid varchar(1),
  fcl_puntos numeric(15,2),
  fcl_clas1 varchar(10),
  fcl_clas2 varchar(10),
  fcl_clas3 varchar(10),
  fcl_clas4 varchar(10),
  fcl_clas5 varchar(10),
  fcl_clas6 varchar(10),
  fcl_clas7 varchar(10),
  fcl_clas8 varchar(10),
  fcl_clas9 varchar(10),
  fcl_clas10 varchar(10),
  fcl_puntosinicial numeric(15,2),
  fcl_tipo_cliente varchar(1),
  fecha_ingreso timestamp,
  inicio_membresia timestamp,
  fin_membresia timestamp,
  fcl_genero varchar(1),
  fcl_aplicatrans varchar(1),
  fcl_codigofacturar numeric(15,0),
  fcl_fee_nacional numeric(10,2),
  fcl_fee_internacional numeric(10,2),
  fcl_fee_intercontinental numeric(10,2),
  fcl_cuota1 integer,
  fcl_cuota2 integer,
  fcl_cuota3 integer,
  fcl_cuota4 integer,
  fcl_cuota5 integer,
  fcl_cuota6 integer,
  fcl_dias_bloqueo integer,
  fcl_aplicadebito varchar(1),
  fcl_numtarjetadebito varchar(30),
  fcl_caducatarjeta varchar(6),
  fcl_sts_dcto_efectivo varchar(1),
  fcl_sts_dcto_cheque varchar(1),
  fcl_sts_dcto_tarjeta varchar(1),
  fcl_sts_dcto_especial varchar(1),
  fcl_sts_dcto_tope_caja varchar(1),
  fcl_dcto_cata numeric(10,2),
  fcl_dcto_catb numeric(10,2),
  fcl_dcto_catc numeric(10,2),
  fcl_sujeto_credito varchar(1),
  fcl_provincia varchar(2),
  fcl_canton varchar(2),
  fcl_parroquia varchar(7),
  fcl_sexo varchar(1),
  fcl_estado_civil varchar(1),
  fcl_origen_ingresos varchar(1),
  fcl_dcto_fijo numeric(10,2),
  fcl_rise varchar(40),
  fcl_limite_original numeric(14,2),
  fcl_numcontribuyenteesp numeric(10,0),
  fcl_obligadocontabilidad varchar(2),
  fcl_mail2 varchar(100),
  fcl_mail3 varchar(100),
  fcl_mail4 varchar(100),
  fcl_mail5 varchar(100),
  fcl_activadcto varchar(1),
  fcl_diferidos varchar(20),
  fcl_devolucion_diferidos varchar(20),
  fcl_parterel varchar(2),
  fcl_vendedor2 integer,
  fcl_creditodiasimpresion integer,
  fcl_id_gestorpm varchar(30),
  fcl_venceproximomes varchar(1),
  fcl_flujo varchar(50),
  fcl_alias varchar(30),
  fcl_facturarcredito varchar(1),
  fcl_password varchar(50),
  fcl_ruta varchar(20),
  fcl_status varchar(1),
  fcl_mail6 varchar(150),
  fcl_mail7 varchar(150),
  fcl_mail8 varchar(150),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer,
  fcl_burocredito varchar(3),
  fcl_calcula_vencimiento varchar(1),
  fcl_operadora varchar(1),
  fcl_estatus_puntos varchar(1),
  fcl_activacion_puntos timestamp,
  fcl_caducidad_puntos timestamp,
  fcl_codigo_inscripcion varchar(100),
  fcl_vigencia_estado timestamp,
  fcl_status_equifax varchar(1),
  fcl_cxc_envio varchar(1),
  fcl_cxc_frecuencia varchar(1),
  fcl_desccuento_15 numeric(12,2),
  fcl_desccuento_0 numeric(12,2),
  fcl_desccuento_30 numeric(12,2),
  fcl_desccuento_90 numeric(12,2),
  fcl_desccuento_60 numeric(12,2),
  fcl_desccuento_120 numeric(12,2),
  fcl_usodatos_autoriza varchar(2),
  fcl_usodatos_usuario varchar(35),
  fcl_usodatos_fecha timestamp
);

-- FAC_VEND (6 filas en origen)
DROP TABLE IF EXISTS public.fac_vend CASCADE;
CREATE TABLE public.fac_vend (
  fve_codigo integer NOT NULL,
  fve_nombre varchar(40),
  fve_direccion varchar(40),
  fve_telefono varchar(15),
  fve_ruc varchar(14),
  fve_activo varchar(1),
  fve_cod_socio varchar(10),
  fve_credito numeric(14,2),
  fve_clave varchar(10),
  fve_admin varchar(1),
  fve_clave_admin varchar(10),
  fve_iniciales varchar(5),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer,
  fve_email varchar(150)
);

-- FAC_CARTERA (24906 filas en origen)
DROP TABLE IF EXISTS public.fac_cartera CASCADE;
CREATE TABLE public.fac_cartera (
  fcc_cuenta numeric(10,0) NOT NULL,
  fve_codigo integer,
  fcl_codigo numeric(15,0),
  fcc_tipo varchar(1),
  fcc_serie numeric(10,0),
  fcc_factura numeric(10,0),
  fcc_fecha timestamp,
  fcc_vend timestamp,
  fcc_valor numeric(15,2),
  fcc_pagado numeric(15,2),
  fcc_sucursal integer,
  fcc_local integer,
  fcc_retencion varchar(1),
  fcc_garantizado numeric(15,2),
  fcc_status varchar(1),
  fcc_gar_id_documento numeric(10,0),
  fcc_gar_banco varchar(10),
  fcc_gar_cuenta varchar(15),
  fcc_gar_cheque varchar(15),
  fcc_ret_fuente numeric(15,2),
  fcc_ret_iva numeric(15,2),
  fcc_pago_comision varchar(1),
  fcc_comision_usuario varchar(10),
  fcc_comision_fecha timestamp,
  fcc_valor_original numeric(12,2),
  fcc_usuario_edita varchar(50),
  fcc_fecha_edita timestamp,
  fcc_edita_cuotas varchar(25),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer
);

-- FAC_CIERRE_CAJA (8012 filas en origen)
DROP TABLE IF EXISTS public.fac_cierre_caja CASCADE;
CREATE TABLE public.fac_cierre_caja (
  cica_numero numeric(10,0) NOT NULL,
  cica_fecha timestamp,
  cica_inicial timestamp,
  cica_final timestamp,
  cica_num_fac_emitida integer,
  cica_num_fac_anuladas integer,
  cica_num_cre_emitido integer,
  cica_num_cre_anulado integer,
  cica_num_ing_emitidos integer,
  cica_num_ing_anula integer,
  cica_fac_efectivo numeric(10,2),
  cica_fac_cheque numeric(10,2),
  cica_fac_tarjeta numeric(10,2),
  cica_fac_credito numeric(10,2),
  cica_fac_cruces numeric(10,2),
  cica_abo_efectivo numeric(10,2),
  cica_abo_cheque numeric(10,2),
  cica_abo_tarjeta numeric(10,2),
  cica_abo_otro numeric(10,2),
  cica_abo_retenciones numeric(10,2),
  cica_cerrado varchar(50),
  cica_observaciones varchar(500),
  cica_serie_factura numeric(10,0),
  cica_serie_nota numeric(10,0),
  cica_serie_comp numeric(10,0),
  cica_fac_retenciones numeric(10,2),
  cica_local integer,
  cica_serie_retenciones integer,
  cica_fac_devolucion numeric(20,6),
  cica_estado_ccc varchar(1),
  cica_capturado_tesoreria varchar(1),
  cica_pax integer,
  cica_mesas_fac integer,
  cica_mesas_sinfac integer,
  cica_mesas integer,
  cica_gastos_consumos numeric(10,2),
  cica_gastos_consumos_cheque numeric(10,2),
  cica_abo_transferencia numeric(10,2),
  cica_num_nd_emitida integer,
  cica_num_nd_anuladas integer,
  cica_serie_debito numeric(10,0),
  cica_nd_efectivo numeric(10,2),
  cica_nd_cheque numeric(10,2),
  cica_nd_tarjeta numeric(10,2),
  cica_nd_credito numeric(10,2),
  cica_nd_cruces numeric(10,2),
  cica_local_numero numeric(10,0),
  cica_transferido varchar(1),
  cica_fac_tjt_regalo numeric(10,2),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer,
  cica_ajusteanticipo numeric(10,2),
  cica_fac_transferencia numeric(10,2),
  cica_fac_deuna numeric(10,2),
  cica_abo_deuna numeric(10,2)
);

-- FAC_RETENCIONES_SRI (12089 filas en origen)
DROP TABLE IF EXISTS public.fac_retenciones_sri CASCADE;
CREATE TABLE public.fac_retenciones_sri (
  frs_secuencial numeric(10,0) NOT NULL,
  frs_numero varchar(20),
  frs_ruc_emisor varchar(13),
  frs_razon_emisor varchar(150),
  frs_fecha_emision timestamp,
  frs_fecha_autorizacion timestamp,
  frs_tipo_emsion varchar(15),
  frs_identificacion_receptor varchar(13),
  frs_clave_acceso varchar(49),
  frs_autorizacion varchar(49),
  frs_estado varchar(1),
  frs_usuario varchar(50),
  frs_fecha timestamp,
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer,
  frs_codigo varchar(5),
  frs_base_imponible numeric(15,2),
  frs_porcentaje numeric(6,2),
  frs_valor numeric(15,2),
  frs_codigo_sustento varchar(2),
  frs_numero_sustento varchar(17),
  frs_fecha_sustento timestamp,
  frs_path_archivo varchar(260),
  fsr_vendedor integer,
  fsr_tipo_porcentaje varchar(1),
  fsr_cod_cliente numeric(15,0),
  fsr_item integer,
  fsr_serie_fact integer,
  fsr_numero_fact numeric(10,0),
  fsr_serie_ing integer,
  fsr_numero_ing numeric(10,0),
  fsr_codigo_sri varchar(5),
  fsr_procesar varchar(1),
  fsr_anulado varchar(1),
  fsr_anulado_por varchar(10),
  fsr_anulado_fecha timestamp
);

-- FAC_COMPRAS (197 filas en origen)
DROP TABLE IF EXISTS public.fac_compras CASCADE;
CREATE TABLE public.fac_compras (
  regcom_serie numeric(10,0) NOT NULL,
  regcom_numero numeric(10,0) NOT NULL,
  regcom_fecha timestamp,
  regcom_proveedor numeric(10,0),
  regcom_factura varchar(25),
  regcom_fecha_factura timestamp,
  regcom_sumam numeric(12,2),
  regcom_descuentos numeric(12,2),
  regcom_subtotal numeric(12,2),
  regcom_subtotal0 numeric(12,2),
  regcom_subtotaliva numeric(12,2),
  regcom_iva numeric(12,2),
  regcom_total numeric(12,2),
  regcom_bienes numeric(12,2),
  regcom_servicios numeric(12,2),
  regcom_realizado varchar(25),
  regcom_revisado varchar(25),
  regcom_autorizado varchar(25),
  regcom_estado varchar(1),
  regcom_motivo varchar(250),
  regcom_fechaanula timestamp,
  regcom_anuladopor varchar(25),
  regcom_diferencias numeric(12,2),
  regcom_cartera numeric(15,0),
  regcom_fecha_cartera timestamp,
  regcom_bodega numeric(10,0),
  regcom_usuariocierre varchar(10),
  regcom_fechacierre timestamp,
  regcom_numero_nc numeric(10,0),
  regcom_subtotal_nc numeric(15,2),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer,
  regcom_condiferencias varchar(1)
);

-- FAC_COMPRA (623 filas en origen)
DROP TABLE IF EXISTS public.fac_compra CASCADE;
CREATE TABLE public.fac_compra (
  comp_serie numeric(10,0) NOT NULL,
  comp_numero numeric(10,0) NOT NULL,
  comp_usuario_reg varchar(10),
  comp_fecha timestamp,
  comp_proveedor numeric(10,0),
  comp_proforma varchar(25),
  comp_observaciones varchar(500),
  comp_subtotal numeric(20,6),
  comp_descuento numeric(20,6),
  comp_iva0 numeric(20,6),
  comp_iva12 numeric(20,6),
  comp_total numeric(20,6),
  comp_realizado varchar(25),
  comp_aprobado varchar(25),
  comp_fecha_reg timestamp,
  comp_codicion_pago varchar(300),
  comp_entrega varchar(40),
  comp_mail varchar(150),
  comp_ciudad varchar(40),
  comp_atencion varchar(40),
  comp_fec_embarque timestamp,
  comp_fec_puerto timestamp,
  comp_fec_bodega timestamp,
  comp_status varchar(1),
  comp_bodega integer,
  comp_ingreso numeric(10,0),
  comp_anulado varchar(1),
  comp_fecha_anul timestamp,
  comp_motivo_anul varchar(1000),
  comp_usuario_anul varchar(10),
  comp_pedido_serie numeric(10,0),
  comp_pedido_numero numeric(10,0),
  comp_fecha_aprueba timestamp,
  comp_usuario_confirma varchar(10),
  comp_fecha_confirma timestamp,
  comp_fecha_entrega timestamp,
  comp_tipo varchar(1),
  comp_serie_prof integer,
  comp_numero_prof numeric(10,0),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer,
  comp_serie_factura integer,
  comp_numero_factura integer,
  comp_pedido_proveedor numeric(10,0),
  comp_referencia_proveedor varchar(50),
  comp_pedido_clase_proveedor varchar(50),
  comp_fecha_factura timestamp,
  comp_texto_factura varchar(50),
  comp_motivo_finaliza varchar(500),
  comp_usuario_finaliza varchar(10),
  comp_fecha_finaliza timestamp
);

-- FAC_COMPRA_DETALLE (6785 filas en origen)
DROP TABLE IF EXISTS public.fac_compra_detalle CASCADE;
CREATE TABLE public.fac_compra_detalle (
  comp_serie numeric(10,0) NOT NULL,
  comp_numero numeric(10,0) NOT NULL,
  deco_item integer NOT NULL,
  deco_codigo varchar(20),
  deco_descripcion varchar(255),
  deco_cantidad numeric(20,6),
  deco_precio numeric(20,6),
  deco_descuento numeric(20,6),
  deco_iva numeric(20,6),
  deco_estado varchar(1),
  deco_serie_fac numeric(10,0),
  deco_numero_fac numeric(10,0),
  deco_registro_fac integer,
  deco_boleto varchar(50),
  deco_fec_embarque timestamp,
  deco_fec_puerto timestamp,
  deco_fec_bodega timestamp,
  deco_status varchar(1),
  deco_bodega integer,
  deco_ingreso numeric(10,0),
  deco_bl varchar(50),
  deco_cajas numeric(20,6),
  deco_precio1 numeric(20,6),
  deco_precio2 numeric(20,6),
  deco_precio3 numeric(20,6),
  deco_precio4 numeric(20,6),
  deco_precio5 numeric(20,6),
  deco_medida varchar(5),
  deco_bodega_inicial integer,
  deco_referencia varchar(20),
  deco_mxcaja numeric(20,6),
  deco_opcion_prof integer,
  deco_item_prof integer,
  deco_bodega_stock integer,
  deco_stock numeric(15,2),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer,
  deco_reservas varchar(50),
  deco_costo_reserva numeric(20,6),
  deco_num_abono varchar(100),
  deco_fecha_abono timestamp,
  deco_costo_abono numeric(20,6),
  deco_fecha_reserva timestamp,
  deco_req_despacho integer,
  deco_reg_insumo integer,
  deco_observacion varchar(300),
  deco_despachado integer,
  deco_entregado integer,
  deco_facturado integer,
  deco_fecha_despachado timestamp,
  deco_fecha_entregado timestamp,
  deco_fecha_facturado timestamp,
  deco_registro_det_factura integer,
  deco_precio_factura numeric(20,6),
  deco_descuento_factura numeric(20,6),
  deco_iva_factura numeric(20,6),
  deco_total_factura numeric(20,6),
  deco_factura_proveedor varchar(20),
  deco_fecha_factura_proveedor timestamp
);

-- FAC_DET_PAGOS_PROVEEDOR (0 filas en origen)
DROP TABLE IF EXISTS public.fac_det_pagos_proveedor CASCADE;
CREATE TABLE public.fac_det_pagos_proveedor (
  fltc_numero numeric(10,0) NOT NULL,
  fdpp_registro integer NOT NULL,
  clm_codigo varchar(10),
  tbs_codigo varchar(20),
  fdpp_valor numeric(12,6),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer
);

-- FAC_CHE_PROVEEDORES (0 filas en origen)
DROP TABLE IF EXISTS public.fac_che_proveedores CASCADE;
CREATE TABLE public.fac_che_proveedores (
  tpr_codigo numeric(10,0) NOT NULL,
  hpr_registro numeric(10,0) NOT NULL,
  fbt_codigo varchar(10),
  hpr_cuenta varchar(25),
  hpr_cheque varchar(25),
  hpr_fecha timestamp,
  hpr_cobrar timestamp,
  hpr_valor numeric(12,2),
  hpr_estado varchar(1),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer
);

-- FAC_STOCK (239849 filas en origen)
DROP TABLE IF EXISTS public.fac_stock CASCADE;
CREATE TABLE public.fac_stock (
  tbs_codigo varchar(20) NOT NULL,
  stk_bodega integer NOT NULL,
  stk_incial numeric(20,6),
  stk_costo numeric(20,6),
  stk_actual numeric(20,6),
  stk_costo_actual numeric(20,6),
  stk_cuenta varchar(20),
  stk_costo_vtas varchar(20),
  stk_ventas varchar(20),
  stk_devoluciones varchar(20),
  stk_descuento varchar(20),
  stk_descuento1 varchar(20),
  stk_descuento2 varchar(20),
  stk_dcto_dvlt varchar(20),
  stk_dcto_dvlt1 varchar(20),
  stk_dcto_dvlt2 varchar(20),
  stk_inventario numeric(20,6),
  stk_maximo numeric(20,6),
  stk_minimo numeric(20,6),
  stk_compra numeric(20,6),
  stk_pro_cantidad numeric(20,6),
  stk_pro_costo numeric(20,6),
  stk_inventarios integer,
  stk_fecha_inventario timestamp,
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer,
  stk_percha1 varchar(25),
  stk_percha2 varchar(25),
  stk_cta_ice varchar(20),
  stk_percha3 varchar(25),
  stk_percha4 varchar(25),
  stk_percha5 varchar(25)
);

-- FAC_BIEN_SERV (3351 filas en origen)
DROP TABLE IF EXISTS public.fac_bien_serv CASCADE;
CREATE TABLE public.fac_bien_serv (
  tbs_codigo varchar(20) NOT NULL,
  unme_codigo varchar(5),
  prim_codigo varchar(20),
  tbs_tipo varchar(1),
  tbs_descripcion varchar(255),
  tbs_descripcion2 varchar(255),
  tbs_saldo_inicial numeric(20,6),
  tbs_costo_inicial numeric(20,6),
  tbs_saldo_actual numeric(20,6),
  tbs_costo_actual numeric(20,6),
  tbs_precio1 numeric(20,6),
  tbs_precio2 numeric(20,6),
  tbs_precio3 numeric(20,6),
  tbs_precio4 numeric(20,6),
  tbs_precio5 numeric(20,6),
  tbs_ventas varchar(20),
  tbs_descuento varchar(20),
  tbs_descuento1 varchar(20),
  tbs_descuento2 varchar(20),
  tbs_devoluciones varchar(20),
  tbs_costo_ventas varchar(20),
  tbs_dcto_dvlt varchar(20),
  tbs_dcto_dvlt1 varchar(20),
  tbs_dcto_dvlt2 varchar(20),
  tbs_unidades numeric(20,6),
  tbs_etiqueta varchar(1),
  tbs_cantidad integer,
  tbs_impresora integer,
  tbs_iva numeric(5,2),
  tbs_costo_aproximado numeric(20,6),
  tbs_alterno varchar(20),
  tbs_alterno2 varchar(20),
  tbs_alterno1 varchar(20),
  tbs_conversion numeric(20,10),
  tbs_objetoiva varchar(1),
  tbs_orden integer,
  tbs_activo varchar(1),
  tbs_meta_unidades1 numeric(20,6),
  tbs_meta_dolares1 numeric(20,6),
  tbs_ly_unidades numeric(20,6),
  tbs_ly_dolares numeric(20,6),
  tbs_meta_unidades2 numeric(20,6),
  tbs_meta_unidades3 numeric(20,6),
  tbs_meta_unidades4 numeric(20,6),
  tbs_meta_unidades5 numeric(20,6),
  tbs_meta_unidades6 numeric(20,6),
  tbs_meta_unidades7 numeric(20,6),
  tbs_meta_unidades8 numeric(20,6),
  tbs_meta_unidades9 numeric(20,6),
  tbs_meta_unidades10 numeric(20,6),
  tbs_meta_unidades11 numeric(20,6),
  tbs_meta_unidades12 numeric(20,6),
  tbs_meta_dolares2 numeric(20,6),
  tbs_meta_dolares3 numeric(20,6),
  tbs_meta_dolares4 numeric(20,6),
  tbs_meta_dolares5 numeric(20,6),
  tbs_meta_dolares6 numeric(20,6),
  tbs_meta_dolares7 numeric(20,6),
  tbs_meta_dolares8 numeric(20,6),
  tbs_meta_dolares9 numeric(20,6),
  tbs_meta_dolares10 numeric(20,6),
  tbs_meta_dolares11 numeric(20,6),
  tbs_meta_dolares12 numeric(20,6),
  tbs_clasificacion1 varchar(50),
  tbs_clasificacion2 varchar(50),
  tbs_puntos numeric(20,6),
  tbs_clas1 varchar(10),
  tbs_clas2 varchar(10),
  tbs_clas3 varchar(10),
  tbs_clas4 varchar(10),
  tbs_clas5 varchar(10),
  tbs_clas6 varchar(10),
  tbs_clas7 varchar(10),
  tbs_clas8 varchar(10),
  tbs_clas9 varchar(10),
  tbs_clas10 varchar(10),
  tbs_formula_terminado varchar(20),
  tbs_formula_cantidad numeric(20,6),
  tbs_formula_bodega numeric(10,0),
  tbs_bodega_factura integer,
  tbs_cajas numeric(20,6),
  tbs_piezas numeric(20,6),
  tbs_dcto_tarjeta numeric(20,6),
  tbs_precio_factor numeric(20,6),
  tbs_inventarios integer,
  tbs_serial varchar(1),
  tbs_costo_promedio numeric(20,6),
  tbs_porcentaje_promedio numeric(20,6),
  tbs_membresia varchar(1),
  tbs_codigo_membresia numeric(6,0),
  tbs_tiempo_estandar numeric(15,2),
  tbs_dcto_tope_caja numeric(10,2),
  tbs_categoria_dcto varchar(1),
  tbs_activa_promocion varchar(1),
  tbs_diferido varchar(1),
  tbs_num_meses integer,
  tbs_diferidos varchar(20),
  tbs_devolucion_diferidos varchar(20),
  tbs_activofijo varchar(1),
  tbs_tipo_descripcion varchar(1),
  tbs_param_precio1 numeric(20,6),
  tbs_param_precio2 numeric(20,6),
  tbs_param_precio3 numeric(20,6),
  tbs_param_precio4 numeric(20,6),
  tbs_param_precio5 numeric(20,6),
  tbs_a_desc_efectivo numeric(20,6),
  tbs_a_desc_tarjeta numeric(20,6),
  tbs_a_desc_credito numeric(20,6),
  tbs_a_desc_credito_lp numeric(20,6),
  tbs_b_desc_efectivo numeric(20,6),
  tbs_b_desc_tarjeta numeric(20,6),
  tbs_b_desc_credito numeric(20,6),
  tbs_b_desc_credito_lp numeric(20,6),
  tbs_c_desc_efectivo numeric(20,6),
  tbs_c_desc_tarjeta numeric(20,6),
  tbs_c_desc_credito numeric(20,6),
  tbs_c_desc_credito_lp numeric(20,6),
  tbs_principio_activo varchar(50),
  tbs_concentracion varchar(50),
  tbs_forma_farmaceutica varchar(50),
  tbs_presentacion varchar(300),
  tbs_fijacion_percio varchar(50),
  tbs_registro_sanitario varchar(50),
  tbs_procedencia varchar(100),
  tbs_registra_lote varchar(1),
  tbs_tipo_med varchar(1),
  tbs_local integer,
  tbs_servicio varchar(1),
  tbs_variedad varchar(10),
  tbs_medidas_peso numeric(20,6),
  tbs_medidas_largo numeric(20,6),
  tbs_medidas_ancho numeric(20,6),
  tbs_medidas_altura numeric(20,6),
  tbs_garantia_detalle varchar(250),
  tbs_garantia_dias integer,
  tbs_formula_origen varchar(20),
  tbs_web varchar(1),
  tbs_terminado varchar(1),
  tbs_barras1 varchar(30),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer,
  tbs_aplica_ice varchar(1),
  tbs_ice_tarifa varchar(1),
  tbs_ice_codigo integer,
  tbs_ice_clasifica integer,
  tbs_ice_marca integer,
  tbs_ice_presentacion integer,
  tbs_ice_capacidad integer,
  tbs_ice_unidad integer,
  tbs_ice_pais integer,
  tbs_ice_grado_alcohol integer,
  tbs_ice_gramos_azucar integer,
  tbs_cta_ice varchar(20),
  tbs_producto_mantenimiento varchar(1),
  tbs_dcto_precio1 numeric(20,6),
  tbs_dcto_precio2 numeric(20,6),
  tbs_dcto_precio3 numeric(20,6),
  tbs_dcto_precio4 numeric(20,6),
  tbs_dcto_precio5 numeric(20,6),
  tbs_asigna_auto varchar(1),
  tbs_tipo_asigna_auto varchar(1),
  tbs_meses_activacion integer,
  tbs_supplier_leadtime integer,
  tbs_supplier_minimumorder numeric(10,0),
  tbs_supplier_multipleorder integer,
  tbs_store_multipleorder integer,
  tbs_store_minimuorder integer,
  tbs_periodicity integer,
  tbs_control_factura varchar(1),
  tbs_codigosri_construccion varchar(20),
  tbs_servicio_arriendo varchar(1),
  tbs_control_costo numeric(20,6),
  tbs_control_tipo varchar(1),
  tbs_control_fecha timestamp,
  tbs_conversion_hp numeric(20,6),
  tbs_codigo_hp varchar(20),
  tbs_oper_conversion_hp varchar(1),
  tbs_cantidad_unme_compra numeric(20,6)
);

-- FAC_LOCALES (3 filas en origen)
DROP TABLE IF EXISTS public.fac_locales CASCADE;
CREATE TABLE public.fac_locales (
  loc_numero integer NOT NULL,
  loc_nombre varchar(300),
  loc_direccion varchar(1000),
  loc_telefono varchar(100),
  loc_ciudad varchar(100),
  loc_observacion varchar(3000),
  loc_formato_factura varchar(100),
  loc_formato_nc varchar(100),
  loc_establecimiento varchar(3),
  loc_items_factura integer,
  loc_items_nc integer,
  loc_servidor varchar(100),
  loc_usuario varchar(100),
  loc_clave varchar(100),
  loc_base varchar(100),
  oc_formato_gure varchar(100),
  loc_bodega integer,
  loc_cover varchar(20),
  loc_cover2 varchar(20),
  loc_cover3 varchar(20),
  loc_peso1 numeric(20,6),
  loc_peso2 numeric(20,6),
  loc_mesa_inicio integer,
  loc_clasificacion varchar(10),
  loc_imp_prefactura integer,
  loc_correo varchar(30),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer,
  loc_codigo varchar(10),
  loc_region varchar(25)
);

-- FAC_MOVIMIENTOS (398172 filas en origen)
DROP TABLE IF EXISTS public.fac_movimientos CASCADE;
CREATE TABLE public.fac_movimientos (
  tbs_codigo varchar(20) NOT NULL,
  stk_bodega integer NOT NULL,
  fmo_tipo integer NOT NULL,
  fmo_numero numeric(10,0) NOT NULL,
  fmo_item numeric(10,0) NOT NULL,
  clm_codigo varchar(10),
  fmo_serie numeric(10,0),
  fmo_fecha timestamp,
  fmo_cantidad numeric(20,6),
  fmo_costo numeric(20,6),
  fmo_descuento numeric(5,2),
  fmo_descuento1 numeric(5,2),
  fmo_descuento2 numeric(5,2),
  fmo_precio numeric(20,6),
  fmo_iva numeric(5,2),
  fmo_conta varchar(20),
  fmo_saldo numeric(20,6),
  fmo_prom numeric(20,6),
  fmo_dcto_neto numeric(20,2),
  fmo_dcto_neto1 numeric(20,2),
  fmo_dcto_neto2 numeric(20,2),
  fmo_iva_neto numeric(20,2),
  fmo_precio_neto numeric(20,2),
  fmo_estandar varchar(1),
  fmo_proyecto varchar(10),
  fmo_concepto varchar(5),
  fmo_diferencia numeric(20,2),
  fmo_porciento numeric(10,6),
  fmo_combo varchar(20),
  fmo_cmb_cantidad numeric(20,6),
  fmo_cmb_precio numeric(20,6),
  fmo_cmb_dcto numeric(10,2),
  fmo_cmb_dcto1 numeric(10,2),
  fmo_cmb_dcto2 numeric(10,2),
  fmo_cmb_iva numeric(10,2),
  fmo_cmb_precio_neto numeric(20,2),
  fmo_cmb_dcto_neto numeric(20,2),
  fmo_cmb_iva_neto numeric(20,2),
  fmo_cmb_valida varchar(1),
  fmo_cajas numeric(20,6),
  fmo_piezas numeric(20,6),
  fmo_lote varchar(10),
  fmo_sts_lote varchar(1),
  fmo_op_numero numeric(10,0),
  fmo_op_serie numeric(10,0),
  fmo_dpch_serie numeric(10,0),
  fmo_dpch_numero numeric(10,0),
  fmo_num_serie varchar(50),
  fmo_observacion varchar(3000),
  fmo_costo_promedio numeric(20,6),
  fmo_porcentaje_promedio numeric(20,6),
  fmo_recargo numeric(20,6),
  fmo_local integer,
  fmo_fre_serie numeric(10,0),
  fmo_fre_numero numeric(10,0),
  fmo_lote_prod varchar(50),
  fmo_tipo_transaccion integer,
  fmo_fecha_original timestamp,
  fmo_costo_standard numeric(20,6),
  fmo_unidades_standard numeric(20,6),
  fmo_descripcion varchar(3000),
  fmo_referencia varchar(20),
  fmo_serie_opt integer,
  fmo_numero_opt numeric(10,0),
  fmo_registro_dopt integer,
  fmo_mxcajas numeric(20,6),
  fmo_pxcajas numeric(20,6),
  fmo_serie_prof integer,
  fmo_numero_prof numeric(10,0),
  control_fec_creacion timestamp,
  control_spid integer,
  fmo_ice_neto numeric(20,2),
  fmo_opcion_prof integer,
  fmo_item_prof integer,
  fmo_ice numeric(5,2),
  fmo_base_ice numeric(20,6),
  fmo_costo_manual numeric(20,6),
  fmo_cod_menu varchar(10),
  fmo_reg_mesa integer,
  fmo_registro_insumo integer,
  fmo_req_despacho integer,
  fmo_reg_auto integer,
  fmo_codigo_proveedor varchar(50),
  fmo_item_compra integer,
  fmo_costo_oc numeric(20,6),
  fmo_despacho_bodega numeric(10,0),
  fmo_registro_det_factura integer,
  fmo_despacho_precio numeric(20,6),
  fmo_despacho_descuento numeric(20,6),
  fmo_despacho_iva numeric(20,6),
  fmo_oc_serie integer,
  fmo_oc_numero numeric(10,0),
  fmo_oc_anulado varchar(1),
  fmo_oc_fecha_anul timestamp,
  fmo_oc_item integer,
  fmo_tipo_despacho varchar(1),
  fmo_reg_secuencial bigint NOT NULL
);

-- BCO (2 filas en origen)
DROP TABLE IF EXISTS public.bco CASCADE;
CREATE TABLE public.bco (
  bco_codigo varchar(15) NOT NULL,
  gct_codigo varchar(2),
  codcta varchar(20),
  bco_cuenta varchar(35),
  bco_saldo numeric(15,2),
  bco_egresos varchar(4),
  bco_ingresos varchar(4),
  bco_anula varchar(4),
  bco_debitos varchar(4),
  bco_creditos varchar(4),
  bco_codigo_modtesoreria varchar(15),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer,
  bco_aplica_ecommerce varchar(1)
);

-- TES_FLUJO (0 filas en origen)
DROP TABLE IF EXISTS public.tes_flujo CASCADE;
CREATE TABLE public.tes_flujo (
  dfl_cuenta varchar(20) NOT NULL,
  flj_registro numeric(10,0) NOT NULL,
  flj_fecha timestamp,
  flj_detalle varchar(250),
  flj_valor numeric(12,2),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer
);

-- TES_CAJA (0 filas en origen)
DROP TABLE IF EXISTS public.tes_caja CASCADE;
CREATE TABLE public.tes_caja (
  dfl_cuenta varchar(20) NOT NULL,
  cja_registro integer NOT NULL,
  valor_01 numeric(15,2),
  valor_02 numeric(15,2),
  valor_03 numeric(15,2),
  valor_04 numeric(15,2),
  valor_05 numeric(15,2),
  valor_06 numeric(15,2),
  valor_07 numeric(15,2),
  valor_08 numeric(15,2),
  valor_09 numeric(15,2),
  valor_10 numeric(15,2),
  valor_11 numeric(15,2),
  valor_12 numeric(15,2),
  valor_13 numeric(15,2),
  valor_14 numeric(15,2),
  valor_15 numeric(15,2),
  valor_16 numeric(15,2),
  valor_17 numeric(15,2),
  valor_18 numeric(15,2),
  valor_19 numeric(15,2),
  valor_20 numeric(15,2),
  valor_21 numeric(15,2),
  valor_22 numeric(15,2),
  valor_23 numeric(15,2),
  valor_24 numeric(15,2),
  valor_25 numeric(15,2),
  valor_26 numeric(15,2),
  valor_27 numeric(15,2),
  valor_28 numeric(15,2),
  valor_29 numeric(15,2),
  valor_30 numeric(15,2),
  id bigint NOT NULL,
  control_fec_creacion timestamp,
  control_spid integer
);
