/**
 * Despliega todas las vistas IA en GestionBI ejecutando SQL directo.
 * Uso: node scripts/deploy-views.mjs
 */
import sql from "mssql";
import { loadAppEnv } from "./load-env.mjs";

loadAppEnv();

const config = {
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: "GestionBI",
  server: process.env.DB_SERVER || "localhost",
  port: parseInt(process.env.DB_PORT || "1433", 10),
  connectionTimeout: 30000,
  requestTimeout: 120000,
  options: { encrypt: false, trustServerCertificate: true, enableArithAbort: true },
};

const pool = await new sql.ConnectionPool(config).connect();

async function run(label, q) {
  try {
    await pool.request().query(q);
    console.log(`  ✓ ${label}`);
  } catch (e) {
    console.error(`  ✖ ${label}: ${e.message}`);
    throw e;
  }
}

console.log("=== Desplegando vistas IA en GestionBI ===\n");

/* 1. Tabla parámetros */
await run("IA_PARAMETROS_NEGOCIO (tabla)", `
  IF OBJECT_ID('dbo.IA_PARAMETROS_NEGOCIO','U') IS NULL
  CREATE TABLE dbo.IA_PARAMETROS_NEGOCIO (
    CLAVE NVARCHAR(64) NOT NULL PRIMARY KEY,
    VALOR_NUMERICO DECIMAL(18,2) NULL,
    VALOR_TEXTO NVARCHAR(500) NULL,
    DESCRIPCION NVARCHAR(500) NULL,
    ACTUALIZADO DATETIME NOT NULL DEFAULT(GETDATE())
  );
`);
await run("IA_PARAMETROS_NEGOCIO (seed)", `
  IF NOT EXISTS(SELECT 1 FROM dbo.IA_PARAMETROS_NEGOCIO WHERE CLAVE=N'COSTOS_FIJOS_MENSUAL_ESTIMADO')
  INSERT INTO dbo.IA_PARAMETROS_NEGOCIO(CLAVE,VALOR_NUMERICO,DESCRIPCION)
  VALUES(N'COSTOS_FIJOS_MENSUAL_ESTIMADO',NULL,N'Monto mensual estimado de gastos fijos.');
`);

/* 2. V_IA_PARAMETROS_NEGOCIO */
await run("V_IA_PARAMETROS_NEGOCIO", `
  CREATE OR ALTER VIEW dbo.V_IA_PARAMETROS_NEGOCIO AS
  SELECT CLAVE, VALOR_NUMERICO, VALOR_TEXTO, DESCRIPCION, ACTUALIZADO
  FROM dbo.IA_PARAMETROS_NEGOCIO;
`);

/* 3. V_MAESTRA_VENTAS (WAREHOUSE + LIVE) */
await run("V_MAESTRA_VENTAS", `
CREATE OR ALTER VIEW dbo.V_MAESTRA_VENTAS AS
SELECT
    v.PERIODO, v.FECHA,
    YEAR(v.FECHA) AS ANIO, MONTH(v.FECHA) AS MES, DAY(v.FECHA) AS DIA,
    DATEPART(WEEK, v.FECHA) AS SEMANA, DATENAME(WEEKDAY, v.FECHA) AS DIA_SEMANA,
    DATEPART(QUARTER, v.FECHA) AS TRIMESTRE,
    v.LOCAL, v.BODEGA, v.NOMBRE_BODEGA,
    ISNULL(v.BIEN_SERVICIO,'B') AS BIEN_SERVICIO,
    v.MOVIMIENTO,
    CAST(v.SERIE AS VARCHAR(20)) AS SERIE, CAST(v.NUMERO AS VARCHAR(20)) AS NUMERO,
    v.CODIGO, v.DESCRIPCION,
    ISNULL(v.CLASIFICACION5,'') AS MARCA,
    ISNULL(v.CLASIFICACION1,'Sin Clasificar') AS LINEA_PRODUCTO,
    ISNULL(v.CLASIFICACION2,'Sin Clasificar') AS CATEGORIA,
    ISNULL(v.CLASIFICACION3,'') AS SUBCATEGORIA,
    ISNULL(v.CLASIFICACION1,'Sin Clasificar') AS CLASIFICACION1,
    ISNULL(v.CLASIFICACION2,'Sin Clasificar') AS CLASIFICACION2,
    ISNULL(v.CLASIFICACION3,'') AS CLASIFICACION3,
    ISNULL(v.RUC,'0000000000') AS RUC,
    ISNULL(v.NOMBRE_COMPLETO,'Sin Nombre') AS CLIENTE,
    ISNULL(v.CIUDAD,'Sin Ciudad') AS CIUDAD,
    ISNULL(v.PROVINCIA,'') AS PROVINCIA,
    ISNULL(v.CANTON,'') AS CANTON,
    ISNULL(v.CLAS_CLIENTE1,'Sin Segmento') AS SEGMENTO_CLIENTE,
    ISNULL(NULLIF(LTRIM(RTRIM(v.CLAS_FACTURA1)),''), ISNULL(v.CLAS_CLIENTE2,'Sin canal')) AS CANAL,
    ISNULL(v.VENDEDOR,'Sin Vendedor') AS VENDEDOR,
    ISNULL(v.CANTIDAD,0) AS CANTIDAD,
    ISNULL(v.VENTA_NETA,0) AS VENTA_NETA,
    ISNULL(v.COSTO, ISNULL(v.CANTIDAD,0)*ISNULL(v.COSTOU,0)) AS COSTO_TOTAL,
    ISNULL(v.COSTO, ISNULL(v.CANTIDAD,0)*ISNULL(v.COSTOU,0)) AS COSTO_LINEA,
    ISNULL(v.VENTA_NETA,0) - ISNULL(v.COSTO, ISNULL(v.CANTIDAD,0)*ISNULL(v.COSTOU,0)) AS UTILIDAD_BRUTA,
    CAST(CASE WHEN ISNULL(v.VENTA_NETA,0)=0 THEN 0
         ELSE (ISNULL(v.VENTA_NETA,0)-ISNULL(v.COSTO,ISNULL(v.CANTIDAD,0)*ISNULL(v.COSTOU,0)))
              /NULLIF(v.VENTA_NETA,0)*100 END AS DECIMAL(18,4)) AS MARGEN_PCT,
    ISNULL(v.PRECIO, ISNULL(v.VENTA_NETA,0)/NULLIF(v.CANTIDAD,0)) AS PRECIO_UNITARIO,
    ISNULL(v.COSTOU,0) AS COSTO_UNITARIO,
    ISNULL(v.DCTO_NETO,0)+ISNULL(v.DCTO_SUBTOTAL_NETO,0) AS DESCUENTO,
    ISNULL(v.IVA,0) AS IVA,
    CASE WHEN ISNULL(v.VENTA_NETA,0)<0 THEN 1 ELSE 0 END AS ES_DEVOLUCION,
    CASE WHEN ISNULL(v.COSTO,ISNULL(v.CANTIDAD,0)*ISNULL(v.COSTOU,0))>ISNULL(v.VENTA_NETA,0) THEN 1 ELSE 0 END AS MARGEN_NEGATIVO,
    'WAREHOUSE' AS ORIGEN
FROM dbo.META_VENTA_NETA AS v

UNION ALL

SELECT
    CONVERT(VARCHAR(6), fmo.FMO_FECHA, 112) AS PERIODO,
    fmo.FMO_FECHA AS FECHA,
    YEAR(fmo.FMO_FECHA) AS ANIO, MONTH(fmo.FMO_FECHA) AS MES, DAY(fmo.FMO_FECHA) AS DIA,
    DATEPART(WEEK, fmo.FMO_FECHA) AS SEMANA, DATENAME(WEEKDAY, fmo.FMO_FECHA) AS DIA_SEMANA,
    DATEPART(QUARTER, fmo.FMO_FECHA) AS TRIMESTRE,
    ISNULL(loc.LOC_NOMBRE, 'Local-'+CAST(fmo.FMO_LOCAL AS VARCHAR(20))) AS LOCAL,
    CAST(fmo.STK_BODEGA AS VARCHAR(20)) AS BODEGA,
    ISNULL(loc.LOC_NOMBRE, 'BOD-'+CAST(fmo.STK_BODEGA AS VARCHAR(20))) AS NOMBRE_BODEGA,
    'B' AS BIEN_SERVICIO,
    CASE fmo.FMO_TIPO WHEN 40 THEN 'FACTURA' WHEN 60 THEN 'NC' ELSE 'OTRO' END AS MOVIMIENTO,
    CAST(fmo.FMO_SERIE AS VARCHAR(20)) AS SERIE, CAST(fmo.FMO_NUMERO AS VARCHAR(20)) AS NUMERO,
    fmo.TBS_CODIGO AS CODIGO,
    ISNULL(fmo.fmo_descripcion, fbs.TBS_DESCRIPCION) AS DESCRIPCION,
    '' AS MARCA,
    ISNULL(fbs.TBS_CLAS1,'Sin Clasificar') AS LINEA_PRODUCTO,
    ISNULL(fbs.TBS_CLAS2,'Sin Clasificar') AS CATEGORIA,
    ISNULL(fbs.TBS_CLAS3,'') AS SUBCATEGORIA,
    ISNULL(fbs.TBS_CLAS1,'Sin Clasificar') AS CLASIFICACION1,
    ISNULL(fbs.TBS_CLAS2,'Sin Clasificar') AS CLASIFICACION2,
    ISNULL(fbs.TBS_CLAS3,'') AS CLASIFICACION3,
    ISNULL(cli.FCL_RUC,'0000000000') AS RUC,
    ISNULL(cli.FCL_NOMBRE_COMPLETO,'Sin Nombre') AS CLIENTE,
    ISNULL(cli.FCL_CIUDAD,'Sin Ciudad') AS CIUDAD,
    '' AS PROVINCIA,
    '' AS CANTON,
    ISNULL(cli.FCL_CLAS1,'Sin Segmento') AS SEGMENTO_CLIENTE,
    ISNULL(cli.FCL_CLAS2,'Sin canal') AS CANAL,
    ISNULL(vnd.FVE_NOMBRE,'Sin Vendedor') AS VENDEDOR,
    fmo.FMO_CANTIDAD AS CANTIDAD,
    ISNULL(fmo.FMO_PRECIO_NETO,0) AS VENTA_NETA,
    ISNULL(fmo.FMO_COSTO*fmo.FMO_CANTIDAD,0) AS COSTO_TOTAL,
    ISNULL(fmo.FMO_COSTO*fmo.FMO_CANTIDAD,0) AS COSTO_LINEA,
    ISNULL(fmo.FMO_PRECIO_NETO,0)-ISNULL(fmo.FMO_COSTO*fmo.FMO_CANTIDAD,0) AS UTILIDAD_BRUTA,
    CAST(CASE WHEN ISNULL(fmo.FMO_PRECIO_NETO,0)=0 THEN 0
         ELSE (ISNULL(fmo.FMO_PRECIO_NETO,0)-ISNULL(fmo.FMO_COSTO*fmo.FMO_CANTIDAD,0))
              /NULLIF(fmo.FMO_PRECIO_NETO,0)*100 END AS DECIMAL(18,4)) AS MARGEN_PCT,
    fmo.FMO_PRECIO AS PRECIO_UNITARIO,
    ISNULL(fmo.FMO_COSTO,0) AS COSTO_UNITARIO,
    ISNULL(fmo.FMO_DCTO_NETO,0) AS DESCUENTO,
    CAST(0 AS DECIMAL(18,2)) AS IVA,
    CASE WHEN ISNULL(fmo.FMO_PRECIO_NETO,0)<0 THEN 1 ELSE 0 END AS ES_DEVOLUCION,
    CASE WHEN ISNULL(fmo.FMO_COSTO*fmo.FMO_CANTIDAD,0)>ISNULL(fmo.FMO_PRECIO_NETO,0) THEN 1 ELSE 0 END AS MARGEN_NEGATIVO,
    'LIVE' AS ORIGEN
FROM banda.dbo.FAC_MOVIMIENTOS fmo
LEFT JOIN banda.dbo.FAC_BIEN_SERV fbs ON fmo.TBS_CODIGO=fbs.TBS_CODIGO
INNER JOIN banda.dbo.FAC_FACTURAS ffg ON fmo.FMO_SERIE=ffg.FFG_SERIE AND fmo.FMO_NUMERO=ffg.FFG_NUMERO
LEFT JOIN banda.dbo.FAC_CLIENTES cli ON ffg.FCL_CODIGO=cli.FCL_CODIGO
LEFT JOIN banda.dbo.FAC_VEND vnd ON ffg.FVE_CODIGO=vnd.FVE_CODIGO
LEFT JOIN banda.dbo.FAC_LOCALES loc ON fmo.FMO_LOCAL=loc.LOC_NUMERO
WHERE ISNULL(ffg.FFG_ANULADO,'N')='N' AND fmo.FMO_TIPO IN (40,60);
`);

/* 4. V_MAESTRA_CARTERA */
await run("V_MAESTRA_CARTERA", `
CREATE OR ALTER VIEW dbo.V_MAESTRA_CARTERA AS
SELECT
    fcc.FCC_SERIE AS SERIE,
    fcc.FCC_FACTURA AS NUMERO_FACTURA,
    fcc.FCC_TIPO AS TIPO_DOCUMENTO,
    fcc.FCC_FECHA AS FECHA_EMISION,
    fcc.FCC_VEND AS FECHA_VENCIMIENTO,
    DATEDIFF(DAY, fcc.FCC_VEND, GETDATE()) AS DIAS_VENCIDO,
    CASE
      WHEN fcc.FCC_VEND >= GETDATE() THEN 'VIGENTE'
      WHEN DATEDIFF(DAY, fcc.FCC_VEND, GETDATE()) <= 30 THEN '1-30 DIAS'
      WHEN DATEDIFF(DAY, fcc.FCC_VEND, GETDATE()) <= 60 THEN '31-60 DIAS'
      WHEN DATEDIFF(DAY, fcc.FCC_VEND, GETDATE()) <= 90 THEN '61-90 DIAS'
      ELSE 'MAS 90 DIAS'
    END AS RANGO_VENCIMIENTO,
    fcc.FCL_CODIGO AS CODIGO_CLIENTE,
    ISNULL(cli.FCL_NOMBRE_COMPLETO,'Sin Nombre') AS CLIENTE,
    ISNULL(cli.FCL_RUC,'0000000000') AS RUC,
    ISNULL(cli.FCL_CIUDAD,'Sin Ciudad') AS CIUDAD,
    ISNULL(CAST(cli.FCL_CLAS1 AS VARCHAR(50)),'Sin Segmento') AS SEGMENTO_CLIENTE,
    ISNULL(cli.FCL_CREDITO,0) AS DIAS_CREDITO,
    ISNULL(cli.FCL_LIMITE,0) AS LIMITE_CREDITO,
    fcc.FVE_CODIGO AS CODIGO_VENDEDOR,
    ISNULL(vnd.FVE_NOMBRE,'Sin Vendedor') AS VENDEDOR,
    fcc.FCC_LOCAL AS LOCAL,
    ISNULL(loc.LOC_NOMBRE,'Local-'+CAST(fcc.FCC_LOCAL AS VARCHAR)) AS NOMBRE_LOCAL,
    ISNULL(fcc.FCC_VALOR,0) AS VALOR_ORIGINAL,
    ISNULL(fcc.fcc_valor_original,0) AS VALOR_FACTURA,
    ISNULL(fcc.FCC_PAGADO,0) AS VALOR_PAGADO,
    ISNULL(fcc.FCC_VALOR,0)-ISNULL(fcc.FCC_PAGADO,0) AS SALDO_PENDIENTE,
    ISNULL(fcc.FCC_GARANTIZADO,0) AS VALOR_GARANTIZADO,
    ISNULL(fcc.fcc_ret_fuente,0) AS RETENCION_FUENTE,
    ISNULL(fcc.fcc_ret_iva,0) AS RETENCION_IVA,
    ISNULL(fcc.FCC_STATUS,'P') AS STATUS,
    CASE fcc.FCC_STATUS WHEN 'P' THEN 'PENDIENTE' WHEN 'C' THEN 'CANCELADO' WHEN 'A' THEN 'ABONADO' ELSE ISNULL(fcc.FCC_STATUS,'') END AS STATUS_DESC,
    ISNULL(fcc.FCC_RETENCION,'N') AS TIENE_RETENCION,
    CAST(GETDATE() AS DATE) AS FECHA_CONSULTA
FROM banda.dbo.FAC_CARTERA fcc
LEFT JOIN banda.dbo.FAC_CLIENTES cli ON fcc.FCL_CODIGO=cli.FCL_CODIGO
LEFT JOIN banda.dbo.FAC_VEND vnd ON fcc.FVE_CODIGO=vnd.FVE_CODIGO
LEFT JOIN banda.dbo.FAC_LOCALES loc ON fcc.FCC_LOCAL=loc.LOC_NUMERO
WHERE ISNULL(fcc.FCC_STATUS,'P') <> 'C';
`);

/* 5. V_MAESTRA_TESORERIA */
await run("V_MAESTRA_TESORERIA", `
CREATE OR ALTER VIEW dbo.V_MAESTRA_TESORERIA AS
SELECT
    tfl.FLJ_REGISTRO AS REGISTRO,
    tfl.FLJ_FECHA AS FECHA,
    YEAR(tfl.FLJ_FECHA) AS ANIO, MONTH(tfl.FLJ_FECHA) AS MES, DAY(tfl.FLJ_FECHA) AS DIA,
    DATEPART(WEEK, tfl.FLJ_FECHA) AS SEMANA,
    DATEPART(QUARTER, tfl.FLJ_FECHA) AS TRIMESTRE,
    CONVERT(VARCHAR(6), tfl.FLJ_FECHA, 112) AS PERIODO,
    tfl.DFL_CUENTA AS CUENTA,
    tfl.FLJ_DETALLE AS CONCEPTO,
    ISNULL(tfl.FLJ_VALOR,0) AS VALOR,
    ABS(ISNULL(tfl.FLJ_VALOR,0)) AS VALOR_ABS,
    CASE WHEN ISNULL(tfl.FLJ_VALOR,0)>=0 THEN 'INGRESO' ELSE 'EGRESO' END AS TIPO_MOVIMIENTO,
    CASE WHEN ISNULL(tfl.FLJ_VALOR,0)>=0 THEN ISNULL(tfl.FLJ_VALOR,0) ELSE 0 END AS INGRESO,
    CASE WHEN ISNULL(tfl.FLJ_VALOR,0)<0 THEN ABS(ISNULL(tfl.FLJ_VALOR,0)) ELSE 0 END AS EGRESO,
    CAST(GETDATE() AS DATE) AS FECHA_CONSULTA
FROM banda.dbo.TES_FLUJO tfl;
`);

/* 6. V_MAESTRA_BANCOS */
await run("V_MAESTRA_BANCOS", `
CREATE OR ALTER VIEW dbo.V_MAESTRA_BANCOS AS
SELECT
    b.BCO_CODIGO AS CTA_CODIGO,
    b.BCO_CUENTA AS CTA_NUMERO,
    ISNULL(b.CODCTA,'') AS CUENTA_NOMBRE,
    ISNULL(b.BCO_SALDO,0) AS SALDO_ACTUAL,
    CAST(GETDATE() AS DATE) AS FECHA_CONSULTA
FROM banda.dbo.BCO b;
`);

/* 7. V_METADATA_SISTEMA (actualizada) */
await run("V_METADATA_SISTEMA", `
CREATE OR ALTER VIEW dbo.V_METADATA_SISTEMA AS
SELECT 'VENTAS_HISTORICO' AS MODULO,
  MIN(YEAR(FECHA)) AS ANIO_MINIMO, MAX(YEAR(FECHA)) AS ANIO_MAXIMO,
  CAST(MIN(FECHA) AS DATE) AS FECHA_DESDE, CAST(MAX(FECHA) AS DATE) AS FECHA_HASTA,
  COUNT(*) AS TOTAL_REGISTROS, COUNT(DISTINCT PERIODO) AS TOTAL_PERIODOS,
  COUNT(DISTINCT LOCAL) AS TOTAL_LOCALES, COUNT(DISTINCT RUC) AS TOTAL_CLIENTES
FROM dbo.META_VENTA_NETA
UNION ALL
SELECT 'VENTAS_LIVE',
  MIN(YEAR(FECHA)), MAX(YEAR(FECHA)),
  CAST(MIN(FECHA) AS DATE), CAST(MAX(FECHA) AS DATE),
  COUNT(*), COUNT(DISTINCT PERIODO),
  COUNT(DISTINCT LOCAL), COUNT(DISTINCT RUC)
FROM dbo.V_MAESTRA_VENTAS WHERE ORIGEN='LIVE'
UNION ALL
SELECT 'CARTERA',
  MIN(YEAR(FECHA_EMISION)), MAX(YEAR(FECHA_EMISION)),
  CAST(MIN(FECHA_EMISION) AS DATE), CAST(MAX(FECHA_VENCIMIENTO) AS DATE),
  COUNT(*), COUNT(DISTINCT CONVERT(VARCHAR(6), FECHA_EMISION, 112)),
  COUNT(DISTINCT LOCAL), COUNT(DISTINCT CODIGO_CLIENTE)
FROM dbo.V_MAESTRA_CARTERA
UNION ALL
SELECT 'CIERRE_CAJA',
  MIN(YEAR(CICA_FECHA)), MAX(YEAR(CICA_FECHA)),
  CAST(MIN(CICA_FECHA) AS DATE), CAST(MAX(CICA_FECHA) AS DATE),
  COUNT(*), COUNT(DISTINCT CONVERT(VARCHAR(6), CICA_FECHA, 112)),
  COUNT(DISTINCT CICA_LOCAL), 0
FROM banda.dbo.FAC_CIERRE_CAJA
UNION ALL
SELECT 'INVENTARIO', YEAR(GETDATE()), YEAR(GETDATE()),
  CAST(GETDATE() AS DATE), CAST(GETDATE() AS DATE),
  COUNT(*), 1, COUNT(DISTINCT stk.STK_BODEGA), COUNT(DISTINCT stk.TBS_CODIGO)
FROM banda.dbo.FAC_STOCK stk JOIN banda.dbo.FAC_BIEN_SERV fbs ON stk.TBS_CODIGO=fbs.TBS_CODIGO WHERE ISNULL(fbs.TBS_ACTIVO,'S')='S'
UNION ALL
SELECT 'TESORERIA',
  MIN(YEAR(FLJ_FECHA)), MAX(YEAR(FLJ_FECHA)),
  CAST(MIN(FLJ_FECHA) AS DATE), CAST(MAX(FLJ_FECHA) AS DATE),
  COUNT(*), COUNT(DISTINCT CONVERT(VARCHAR(6), FLJ_FECHA, 112)), 0, 0
FROM banda.dbo.TES_FLUJO
UNION ALL
SELECT 'BANCOS_SALDOS', YEAR(GETDATE()), YEAR(GETDATE()),
  CAST(GETDATE() AS DATE), CAST(GETDATE() AS DATE),
  COUNT(*), 1, COUNT(*), 0
FROM banda.dbo.BCO
UNION ALL
SELECT 'PARAMETROS_IA', YEAR(GETDATE()), YEAR(GETDATE()),
  CAST(GETDATE() AS DATE), CAST(GETDATE() AS DATE),
  COUNT(*), 1, 0, 0
FROM dbo.IA_PARAMETROS_NEGOCIO;
`);

/* 8. Inventario + cierre caja (sin cambios pero asegurar que existan) */
await run("V_MAESTRA_CIERRE_CAJA", `
CREATE OR ALTER VIEW dbo.V_MAESTRA_CIERRE_CAJA AS
SELECT
    c.CICA_NUMERO AS NUMERO_CIERRE, c.CICA_FECHA,
    YEAR(c.CICA_FECHA) AS ANIO, MONTH(c.CICA_FECHA) AS MES, DAY(c.CICA_FECHA) AS DIA,
    DATEPART(WEEK, c.CICA_FECHA) AS SEMANA, DATEPART(QUARTER, c.CICA_FECHA) AS TRIMESTRE,
    c.CICA_INICIAL AS HORA_APERTURA, c.CICA_FINAL AS HORA_CIERRE,
    c.CICA_LOCAL, ISNULL(loc.LOC_NOMBRE,'Local-'+CAST(c.CICA_LOCAL AS VARCHAR)) AS NOMBRE_LOCAL,
    ISNULL(c.CICA_NUM_FAC_EMITIDA,0) AS NUM_FACTURAS,
    ISNULL(c.CICA_NUM_FAC_ANULADAS,0) AS NUM_FACTURAS_ANULADAS,
    ISNULL(c.CICA_NUM_CRE_EMITIDO,0) AS NUM_NC_EMITIDAS,
    ISNULL(c.CICA_NUM_CRE_ANULADO,0) AS NUM_NC_ANULADAS,
    ISNULL(c.CICA_FAC_EFECTIVO,0) AS VENTAS_EFECTIVO,
    ISNULL(c.CICA_FAC_CHEQUE,0) AS VENTAS_CHEQUE,
    ISNULL(c.CICA_FAC_TARJETA,0) AS VENTAS_TARJETA,
    ISNULL(c.CICA_FAC_CREDITO,0) AS VENTAS_CREDITO,
    ISNULL(c.CICA_FAC_TRANSFERENCIA,0) AS VENTAS_TRANSFERENCIA,
    ISNULL(c.CICA_FAC_DEVOLUCION,0) AS VENTAS_DEVOLUCION,
    ISNULL(c.CICA_FAC_DEUNA,0) AS VENTAS_DEUNA,
    ISNULL(c.CICA_FAC_EFECTIVO,0)+ISNULL(c.CICA_FAC_CHEQUE,0)+ISNULL(c.CICA_FAC_TARJETA,0)
      +ISNULL(c.CICA_FAC_CREDITO,0)+ISNULL(c.CICA_FAC_TRANSFERENCIA,0)+ISNULL(c.CICA_FAC_DEUNA,0) AS TOTAL_VENTAS,
    ISNULL(c.CICA_ABO_EFECTIVO,0) AS ABONO_EFECTIVO,
    ISNULL(c.CICA_ABO_CHEQUE,0) AS ABONO_CHEQUE,
    ISNULL(c.CICA_ABO_TARJETA,0) AS ABONO_TARJETA,
    ISNULL(c.CICA_ABO_TRANSFERENCIA,0) AS ABONO_TRANSFERENCIA,
    ISNULL(c.CICA_ABO_RETENCIONES,0) AS ABONO_RETENCIONES,
    ISNULL(c.CICA_ABO_OTRO,0) AS ABONO_OTRO,
    ISNULL(c.CICA_ABO_DEUNA,0) AS ABONO_DEUNA,
    ISNULL(c.CICA_GASTOS_CONSUMOS,0) AS GASTOS_CONSUMOS,
    ISNULL(c.CICA_GASTOS_CONSUMOS_CHEQUE,0) AS GASTOS_CONSUMOS_CHEQUE,
    ISNULL(c.CICA_PAX,0) AS NUM_PAX,
    ISNULL(c.CICA_MESAS,0) AS NUM_MESAS,
    ISNULL(c.CICA_MESAS_FAC,0) AS MESAS_FACTURADAS,
    ISNULL(c.CICA_MESAS_SINFAC,0) AS MESAS_SIN_FACTURA,
    c.CICA_CERRADO AS CERRADO,
    c.CICA_OBSERVACIONES AS OBSERVACIONES
FROM banda.dbo.FAC_CIERRE_CAJA c
LEFT JOIN banda.dbo.FAC_LOCALES loc ON c.CICA_LOCAL=loc.LOC_NUMERO;
`);

console.log("\n=== Verificación final ===\n");
const vr = await pool.request().query(
  "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA='dbo' ORDER BY TABLE_NAME"
);
for (const v of vr.recordset) console.log(`  ✓ ${v.TABLE_NAME}`);

const tr = await pool.request().query(
  "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_TYPE='BASE TABLE' ORDER BY TABLE_NAME"
);
console.log("\nTablas:");
for (const t of tr.recordset) console.log(`  ${t.TABLE_NAME}`);

await pool.close();
console.log("\n=== Deploy completo ===");
