/**
 * Catálogo único de preguntas (fuente para tests y para regenerar tablas en preguntas.md).
 * IDs: A01–A10, B01–B08, C01–C13, D01–D10, E01–E10, F01–F10, G01–G10, H01–H10,
 *      I01–I10, J01–J10, K01–K10, L01–L10
 */
export const PREGUNTAS_CATALOG = [
  // A — Clientes, ventas e ingresos
  ["A", "Área comercial — A. Clientes, ventas e ingresos", [
    "¿Cuáles son las ventas totales del mes actual?",
    "¿Cómo se comparan las ventas de este mes vs el mismo mes del año anterior?",
    "¿Cuál es el crecimiento acumulado de ventas en el año?",
    "¿Ventas por línea de producto en el período seleccionado?",
    "¿Ventas por canal (retail, corporativo, online)?",
    "¿Ventas por vendedor o ejecutivo comercial?",
    "¿Top 10 clientes por facturación?",
    "¿Qué clientes han reducido sus compras respecto al período anterior?",
    "¿Cuáles son los clientes nuevos del mes?",
    "¿Cuánto representa cada cliente en el total de ventas (%)?",
  ]],
  ["B", "Área comercial — B. Rentabilidad", [
    "¿Margen bruto por producto o servicio?",
    "¿Margen bruto por cliente?",
    "¿Productos con margen negativo?",
    "¿Rentabilidad por canal de ventas?",
    "¿Ticket promedio por cliente?",
    "¿Ticket promedio por vendedor?",
    "¿Costo de ventas asociado a cada producto?",
    "¿Ventas que no cubren costos fijos?",
  ]],
  ["C", "Área comercial — C. Gestión comercial", [
    "¿Facturas emitidas y pendientes de cobro?",
    "¿Ventas anuladas o notas de crédito del período?",
    "¿Descuentos otorgados por cliente o vendedor?",
    "¿Descuentos promedio sobre ventas?",
    "¿Ventas concentradas en pocos clientes (riesgo)?",
    "¿Clientes inactivos en los últimos 3/6/12 meses?",
    "¿Proyección de ventas al cierre del mes?",
    "¿Proyección de ventas al cierre del año?",
    "¿Ventas facturadas pero no cobradas?",
    "¿Ventas sujetas a retención?",
    "¿Ventas gravadas y exentas de IVA?",
    "¿Alertas de caída significativa de ventas?",
    "¿Dame un resumen de los cierres de caja?",
  ]],
  ["D", "Crédito — D. Cuentas por cobrar", [
    "¿Cuentas por cobrar totales?",
    "¿Antigüedad de cartera (0–30, 31–60, 61–90, +90)?",
    "¿Clientes con cartera vencida?",
    "¿Top clientes morosos?",
    "¿Cobros realizados en el período?",
    "¿Cobros proyectados próximos 30 días?",
    "¿Facturas próximas a vencer?",
    "¿Índice de rotación de cartera?",
    "¿Días promedio de cobro (DSO)?",
    "¿Riesgo de incobrabilidad por cliente?",
  ]],
  ["E", "Cuentas por pagar — E. Cuentas por pagar", [
    "¿Cuentas por pagar totales?",
    "¿Proveedores pendientes de pago?",
    "¿Pagos programados próximos 7/15/30 días?",
    "¿Antigüedad de cuentas por pagar?",
    "¿Proveedores críticos por monto?",
    "¿Pagos vencidos?",
    "¿Pagos recurrentes mensuales?",
    "¿Impacto en caja de pagos futuros?",
    "¿Capacidad de pago a corto plazo?",
    "¿Alertas de estrés de liquidez?",
  ]],
  ["F", "Inventarios — F. Existencias", [
    "¿Stock disponible por producto hoy?",
    "¿Stock por bodega o ubicación?",
    "¿Inventario total valorizado al costo?",
    "¿Inventario valorizado a precio de venta?",
    "¿Productos con stock bajo el mínimo?",
    "¿Productos con sobrestock?",
    "¿Unidades ingresadas y salidas en el período?",
    "¿Inventario comprometido (ventas pendientes de despacho)?",
    "¿Inventario disponible real?",
    "¿Variación de inventario vs mes anterior?",
  ]],
  ["G", "Inventarios — G. Costos y valoración", [
    "¿Costo promedio por producto?",
    "¿Costo última compra?",
    "¿Variación del costo de inventarios?",
    "¿Productos con mayor impacto en el costo total?",
    "¿Diferencias entre inventario físico y contable?",
    "¿Ajustes de inventario realizados en el período?",
    "¿Inventario afectado por mermas o pérdidas?",
    "¿Valor de inventario deteriorado u obsoleto?",
    "¿Inventario provisionado contablemente?",
    "¿Impacto del inventario en el costo de ventas?",
  ]],
  ["H", "Inventarios — H. Rotación y eficiencia", [
    "¿Rotación de inventarios por producto?",
    "¿Días promedio de inventario (DIO)?",
    "¿Productos de alta rotación?",
    "¿Productos de baja rotación?",
    "¿Inventario inmovilizado (+90 / +180 días)?",
    "¿Productos sin movimiento en el período?",
    "¿Relación inventario vs ventas?",
    "¿Nivel óptimo de inventario estimado?",
    "¿Riesgo de quiebre de stock próximo?",
    "¿Recomendación automática de reposición?",
  ]],
  ["I", "Tesorería — I. Caja y bancos", [
    "¿Saldo disponible en bancos hoy?",
    "¿Saldo por cada cuenta bancaria?",
    "¿Saldo en caja chica?",
    "¿Conciliaciones bancarias pendientes?",
    "¿Movimientos bancarios del día/semana/mes?",
    "¿Ingresos y egresos del período?",
    "¿Flujo neto de efectivo del mes?",
    "¿Variación de caja respecto al mes anterior?",
    "¿Ingresos no identificados en bancos?",
    "¿Pagos realizados hoy?",
  ]],
  ["J", "Estados financieros — J. Estado de resultados", [
    "¿Utilidad o pérdida del mes?",
    "¿Utilidad acumulada del año?",
    "¿Comparativo de resultados vs presupuesto?",
    "¿Variación de ingresos vs período anterior?",
    "¿Variación de costos vs período anterior?",
    "¿Gastos administrativos del mes?",
    "¿Gastos no deducibles identificados?",
    "¿Resultado operativo (EBIT)?",
    "¿Margen operativo?",
    "¿Margen neto?",
  ]],
  ["K", "Estados financieros — K. Balance general", [
    "¿Total de activos, pasivos y patrimonio?",
    "¿Composición del activo corriente?",
    "¿Nivel de endeudamiento?",
    "¿Pasivo corriente vs activo corriente?",
    "¿Capital de trabajo?",
    "¿Inventarios por categoría?",
    "¿Activos fijos netos?",
    "¿Depreciación acumulada?",
    "¿Préstamos vigentes y saldos?",
    "¿Obligaciones tributarias pendientes?",
  ]],
  ["L", "Estados financieros — L. Indicadores financieros", [
    "¿Liquidez corriente?",
    "¿Prueba ácida?",
    "¿Rotación de inventarios?",
    "¿Rotación de activos?",
    "¿ROA (rentabilidad sobre activos)?",
    "¿ROE (rentabilidad sobre patrimonio)?",
    "¿Apalancamiento financiero?",
    "¿Punto de equilibrio estimado?",
    "¿Alertas de deterioro financiero?",
    "¿Proyección financiera a 3/6/12 meses?",
  ]],
];

/** Lista plana { id, section, question } */
export function flattenCatalog() {
  const out = [];
  for (const [letter, section, qs] of PREGUNTAS_CATALOG) {
    qs.forEach((q, i) => {
      const n = String(i + 1).padStart(2, "0");
      out.push({ id: `${letter}${n}`, section, question: q });
    });
  }
  return out;
}
